export const countryCodes = [
  // الدول العربية - تبقى بالعربية
  { name: "الأردن", code: "+962", flag: "🇯🇴" },
  { name: "الإمارات", code: "+971", flag: "🇦🇪" },
  { name: "البحرين", code: "+973", flag: "🇧🇭" },
  { name: "الجزائر", code: "+213", flag: "🇩🇿" },
  { name: "السعودية", code: "+966", flag: "🇸🇦" },
  { name: "السودان", code: "+249", flag: "🇸🇩" },
  { name: "الصومال", code: "+252", flag: "🇸🇴" },
  { name: "العراق", code: "+964", flag: "🇮🇶" },
  { name: "الكويت", code: "+965", flag: "🇰🇼" },
  { name: "المغرب", code: "+212", flag: "🇲🇦" },
  { name: "اليمن", code: "+967", flag: "🇾🇪" },
  { name: "تونس", code: "+216", flag: "🇹🇳" },
  { name: "جيبوتي", code: "+253", flag: "🇩🇯" },
  { name: "سوريا", code: "+963", flag: "🇸🇾" },
  { name: "عُمان", code: "+968", flag: "🇴🇲" },
  { name: "فلسطين", code: "+970", flag: "🇵🇸" },
  { name: "قطر", code: "+974", flag: "🇶🇦" },
  { name: "لبنان", code: "+961", flag: "🇱🇧" },
  { name: "ليبيا", code: "+218", flag: "🇱🇾" },
  { name: "مصر", code: "+20", flag: "🇪🇬" },
  { name: "موريتانيا", code: "+222", flag: "🇲🇷" },

  // باقي دول العالم بلغاتها الأصلية
  { name: "Afghanistan", code: "+93", flag: "🇦🇫" },
  { name: "Shqipëria", code: "+355", flag: "🇦🇱" },
  { name: "Algérie", code: "+213", flag: "🇩🇿" },
  { name: "Andorra", code: "+376", flag: "🇦🇩" },
  { name: "Angola", code: "+244", flag: "🇦🇴" },
  { name: "Antigua and Barbuda", code: "+1", flag: "🇦🇬" },
  { name: "Argentina", code: "+54", flag: "🇦🇷" },
  { name: "Հայաստան", code: "+374", flag: "🇦🇲" },
  { name: "Australia", code: "+61", flag: "🇦🇺" },
  { name: "Österreich", code: "+43", flag: "🇦🇹" },
  { name: "Azərbaycan", code: "+994", flag: "🇦🇿" },
  { name: "България", code: "+359", flag: "🇧🇬" },
  { name: "Brasil", code: "+55", flag: "🇧🇷" },
  { name: "Cambridge", code: "+1", flag: "🇨🇦" },
  { name: "Česká republika", code: "+420", flag: "🇨🇿" },
  { name: "中国", code: "+86", flag: "🇨🇳" },
  { name: "Danmark", code: "+45", flag: "🇩🇰" },
  { name: "مصر", code: "+20", flag: "🇪🇬" },
  { name: "England", code: "+44", flag: "🇬🇧" },
  { name: "España", code: "+34", flag: "🇪🇸" },
  { name: "Suomi", code: "+358", flag: "🇫🇮" },
  { name: "France", code: "+33", flag: "🇫🇷" },
  { name: "Deutschland", code: "+49", flag: "🇩🇪" },
  { name: "Ελλάδα", code: "+30", flag: "🇬🇷" },
  { name: "Magyar", code: "+36", flag: "🇭🇺" },
  { name: "Ísland", code: "+354", flag: "🇮🇸" },
  { name: "भारत", code: "+91", flag: "🇮🇳" },
  { name: "Indonesia", code: "+62", flag: "🇮🇩" },
  { name: "ایران", code: "+98", flag: "🇮🇷" },
  { name: "Éire", code: "+353", flag: "🇮🇪" },
  { name: "Italia", code: "+39", flag: "🇮🇹" },
  { name: "日本", code: "+81", flag: "🇯🇵" },
  { name: "Қазақстан", code: "+7", flag: "🇰🇿" },
  { name: "한국", code: "+82", flag: "🇰🇷" },
  { name: "Latvija", code: "+371", flag: "🇱🇻" },
  { name: "Lietuva", code: "+370", flag: "🇱🇹" },
  { name: "Malaysia", code: "+60", flag: "🇲🇾" },
  { name: "México", code: "+52", flag: "🇲🇽" },
  { name: "Nederland", code: "+31", flag: "🇳🇱" },
  { name: "New Zealand", code: "+64", flag: "🇳🇿" },
  { name: "Norge", code: "+47", flag: "🇳🇴" },
  { name: "پاکستان", code: "+92", flag: "🇵🇰" },
  { name: "Philippines", code: "+63", flag: "🇵🇭" },
  { name: "Polska", code: "+48", flag: "🇵🇱" },
  { name: "Portugal", code: "+351", flag: "🇵🇹" },
  { name: "România", code: "+40", flag: "🇷🇴" },
  { name: "Россия", code: "+7", flag: "🇷🇺" },
  { name: "السعودية", code: "+966", flag: "🇸🇦" },
  { name: "Србија", code: "+381", flag: "🇷🇸" },
  { name: "Singapore", code: "+65", flag: "🇸🇬" },
  { name: "Slovensko", code: "+421", flag: "🇸🇰" },
  { name: "Slovenija", code: "+386", flag: "🇸🇮" },
  { name: "South Africa", code: "+27", flag: "🇿🇦" },
  { name: "Sverige", code: "+46", flag: "🇸🇪" },
  { name: "Schweiz", code: "+41", flag: "🇨🇭" },
  { name: "台灣", code: "+886", flag: "🇹🇼" },
  { name: "ประเทศไทย", code: "+66", flag: "🇹🇭" },
  { name: "Türkiye", code: "+90", flag: "🇹🇷" },
  { name: "Україна", code: "+380", flag: "🇺🇦" },
  { name: "United States", code: "+1", flag: "🇺🇸" },
  { name: "O'zbekiston", code: "+998", flag: "🇺🇿" },
  { name: "Việt Nam", code: "+84", flag: "🇻🇳" },
  { name: "Botswana", code: "+267", flag: "🇧🇼" },
  { name: "Burkina Faso", code: "+226", flag: "🇧🇫" },
  { name: "Burundi", code: "+257", flag: "🇧🇮" },
  { name: "Cameroon", code: "+237", flag: "🇨🇲" },
  { name: "Cabo Verde", code: "+238", flag: "🇨🇻" },
  { name: "Centrafrique", code: "+236", flag: "🇨🇫" },
  { name: "Tchad", code: "+235", flag: "🇹🇩" },
  { name: "Chile", code: "+56", flag: "🇨🇱" },
  { name: "Colombia", code: "+57", flag: "🇨🇴" },
  { name: "Comores", code: "+269", flag: "🇰🇲" },
  { name: "République du Congo", code: "+242", flag: "🇨🇬" },
  { name: "Costa Rica", code: "+506", flag: "🇨🇷" },
  { name: "Côte d'Ivoire", code: "+225", flag: "🇨🇮" },
  { name: "Hrvatska", code: "+385", flag: "🇭🇷" },
  { name: "Cuba", code: "+53", flag: "🇨🇺" },
  { name: "Κύπρος", code: "+357", flag: "🇨🇾" },
  { name: "Djibouti", code: "+253", flag: "🇩🇯" },
  { name: "Ecuador", code: "+593", flag: "🇪🇨" },
  { name: "El Salvador", code: "+503", flag: "🇸🇻" },
  { name: "Eritrea", code: "+291", flag: "🇪🇷" },
  { name: "Eswatini", code: "+268", flag: "🇸🇿" },
  { name: "Gabon", code: "+241", flag: "🇬🇦" },
  { name: "Ghana", code: "+233", flag: "🇬🇭" },
  { name: "Guatemala", code: "+502", flag: "🇬🇹" },
  { name: "Guinée", code: "+224", flag: "🇬🇳" },
  { name: "Guiné-Bissau", code: "+245", flag: "🇬🇼" },
  { name: "Guyana", code: "+592", flag: "🇬🇾" },
  { name: "Haïti", code: "+509", flag: "🇭🇹" },
  { name: "Honduras", code: "+504", flag: "🇭🇳" },
  { name: "香港", code: "+852", flag: "🇭🇰" },
  { name: "Jamaica", code: "+1", flag: "🇯🇲" },
  { name: "Kenya", code: "+254", flag: "🇰🇪" },
  { name: "Kiribati", code: "+686", flag: "🇰🇮" },
  { name: "Кыргызстан", code: "+996", flag: "🇰🇬" },
  { name: "ລາວ", code: "+856", flag: "🇱🇦" },
  { name: "Lesotho", code: "+266", flag: "🇱🇸" },
  { name: "Liberia", code: "+231", flag: "🇱🇷" },
  { name: "Liechtenstein", code: "+423", flag: "🇱🇮" },
  { name: "Luxemburg", code: "+352", flag: "🇱🇺" },
  { name: "Македонија", code: "+389", flag: "🇲🇰" },
  { name: "Madagascar", code: "+261", flag: "🇲🇬" },
  { name: "Malawi", code: "+265", flag: "🇲🇼" },
  { name: "Maldives", code: "+960", flag: "🇲🇻" },
  { name: "Mali", code: "+223", flag: "🇲🇱" },
  { name: "Malta", code: "+356", flag: "🇲🇹" },
  { name: "Marshall Islands", code: "+692", flag: "🇲🇭" },
  { name: "Mauritius", code: "+230", flag: "🇲🇺" },
  { name: "Micronesia", code: "+691", flag: "🇫🇲" },
  { name: "Moldova", code: "+373", flag: "🇲🇩" },
  { name: "Monaco", code: "+377", flag: "🇲🇨" },
  { name: "Монгол улс", code: "+976", flag: "🇲🇳" },
  { name: "Црна Гора", code: "+382", flag: "🇲🇪" },
  { name: "Moçambique", code: "+258", flag: "🇲🇿" },
  { name: "Myanmar", code: "+95", flag: "🇲🇲" },
  { name: "Namibia", code: "+264", flag: "🇳🇦" },
  { name: "Nauru", code: "+674", flag: "🇳🇷" },
  { name: "नेपाल", code: "+977", flag: "🇳🇵" },
  { name: "Nicaragua", code: "+505", flag: "🇳🇮" },
  { name: "Niger", code: "+227", flag: "🇳🇪" },
  { name: "Nigeria", code: "+234", flag: "🇳🇬" },
  { name: "Panamá", code: "+507", flag: "🇵🇦" },
  { name: "Papua Niugini", code: "+675", flag: "🇵🇬" },
  { name: "Paraguay", code: "+595", flag: "🇵🇾" },
  { name: "Perú", code: "+51", flag: "🇵🇪" },
  { name: "Rwanda", code: "+250", flag: "🇷🇼" },
  { name: "Samoa", code: "+685", flag: "🇼🇸" },
  { name: "San Marino", code: "+378", flag: "🇸🇲" },
  { name: "São Tomé e Príncipe", code: "+239", flag: "🇸🇹" },
  { name: "Seychelles", code: "+248", flag: "🇸🇨" },
  { name: "Sierra Leone", code: "+232", flag: "🇸🇱" },
  { name: "Solomon Islands", code: "+677", flag: "🇸🇧" },
  { name: "Soomaaliya", code: "+252", flag: "🇸🇴" },
  { name: "Timor-Leste", code: "+670", flag: "🇹🇱" },
  { name: "Togo", code: "+228", flag: "🇹🇬" },
  { name: "Tonga", code: "+676", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", code: "+1", flag: "🇹🇹" },
  { name: "Tuvalu", code: "+688", flag: "🇹🇻" },
  { name: "Uganda", code: "+256", flag: "🇺🇬" },
  { name: "Uruguay", code: "+598", flag: "🇺🇾" },
  { name: "Vanuatu", code: "+678", flag: "🇻🇺" },
  { name: "Vatican City", code: "+379", flag: "🇻🇦" },
  { name: "Venezuela", code: "+58", flag: "🇻🇪" },
  { name: "Zambia", code: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "+263", flag: "🇿🇼" }
];
